### ISSUE TITLE
how does it work?

### ISSUE THREAD

**Issue by logicminds** [puppetlabs/puppetlabs-netscaler#47]
This module looks awesome.  Can you detail how it works?  Does it run directly on the netscaler or is there some sort of proxy puppet agent.  Which models and firmware versions does it support?  What does one need to use this?

**Comment by hunner** [comment]
This module has not yet been released as it is still under heavy development, but any feedback on it would be great :)

The module is a `puppet device` module which works by having a proxy host talking to the netscaler via the rest api, similar to how our cisco/junos/f5 modules work, as the netscaler cannot directly run puppet. Puppet device does not yet have full documentation, but you can read http://puppetlabs.com/blog/puppet-network-device-management and https://docs.puppetlabs.com/puppet/latest/reference/config_file_device.html and https://docs.puppetlabs.com/references/latest/man/device.html for some information on it.

Initial documentation for this module has not been merged yet, but you can see the draft form at https://github.com/laurenrother/puppetlabs-netscaler/tree/readme

We are developing against netscaler 10.5. You need a puppet master to compile the catalogs, and optionally a puppet agent to act as the proxy (or you can run `puppet device` from the master).

Please open further inqueries at https://tickets.puppetlabs.com/browse/MODULES , as that is the official module ticket tracking location.
